In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)
# Define the AdaBoost classifier
clf = MultiOutputClassifier(AdaBoostClassifier(random_state=42))

# Train the classifier
clf.fit(X_train, y_train)

# Memprediksi pada test set
y_pred = clf.predict(X_test)
accuracy = accuracy_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))
print("\nAccuracy:", accuracy)


c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(



Accuracy: 1.0


In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf, x, y, cv=10)
conf_mat = confusion_matrix(y, y_pred)

In [10]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import make_scorer

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

# Define the AdaBoost classifier
clf = MultiOutputClassifier(AdaBoostClassifier(random_state=42))

# Define accuracy as the metric for scoring
scorer = make_scorer(accuracy_score)

# Perform K-fold cross validation
cv_scores = cross_val_score(clf, X, y_encoded, cv=5, scoring=scorer)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)

# Print the mean cross-validation score
print("Mean Cross-validation score:", np.mean(cv_scores))


c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Cross-validation scores: [1. 1. 1. 1. 1.]
Mean Cross-validation score: 1.0


In [11]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

# Define the AdaBoost classifier
clf = MultiOutputClassifier(AdaBoostClassifier(random_state=42))

# Perform K-fold cross validation
cv_scores = cross_val_score(clf, X, y_encoded, cv=5, scoring=None, fit_params=None, n_jobs=1, verbose=0, pre_dispatch='2*n_jobs', error_score='raise')

# Extract the column labels for the encoded target variable
column_labels = enc.categories_[0]

# Print the cross-validation confusion matrices
for i, cv_score in enumerate(cv_scores):
    clf.fit(X, y_encoded)
    y_pred = clf.predict(X)

    # Convert binary predictions to labels
    y_pred_labels = np.vectorize(column_labels.take)(y_pred.argmax(axis=1))

    # Cast label types to string
    y_pred_labels = y_pred_labels.astype(str)

    # Compute the confusion matrix
    cm = confusion_matrix(y_encoded.argmax(axis=1).astype(str), y_pred_labels)

    print(f"Fold {i+1} Confusion Matrix:")
    print(cm)

c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Fold 1 Confusion Matrix:
[[0 0 0 3 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Fold 2 Confusion Matrix:
[[0 0 0 3 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Fold 3 Confusion Matrix:
[[0 0 0 3 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Fold 4 Confusion Matrix:
[[0 0 0 3 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Fold 5 Confusion Matrix:
[[0 0 0 3 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import make_scorer, balanced_accuracy_score
import numpy as np

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

# Define the AdaBoost classifier
clf = MultiOutputClassifier(AdaBoostClassifier(random_state=42))

# Define balanced accuracy as the metric for scoring
scorer = make_scorer(balanced_accuracy_score)

# Perform K-fold cross validation
cv_scores = cross_val_score(clf, X, y_encoded, cv=5, scoring=scorer)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)

# Print the mean cross-validation score
print("Mean Cross-validation score:", np.mean(cv_scores))

# Perform K-fold cross validation with confusion matrix
def compute_confusion_matrix(y_true, y_pred, labels):
    """Compute the confusion matrix for a multi-output classification problem.

    Args:
        y_true (array-like): The true labels.
        y_pred (array-like): The predicted labels.
        labels (list): The list of labels.

    Returns:
        array-like: The confusion matrix.
    """
    n_classes = len(labels)
    conf_mat = np.zeros((n_classes, n_classes))
    for i in range(n_classes):
        for j in range(n_classes):
            conf_mat[i, j] = confusion_matrix(y_true[:, i], y_pred[:, i] == labels[j], labels=labels[i])[0, 1]
    return conf_mat

# Compute the confusion matrix for each fold
conf_mats = []
for i in range(5):
    y_pred = clf.fit(X, y_encoded).predict(X)
    conf_mat = compute_confusion_matrix(y, y_pred, labels=enc.categories_[0])
    conf_mats.append(conf_mat)

# Compute the mean confusion matrix
mean_conf_mat = np.mean(conf_mats, axis=0)

# Print the mean confusion matrix
print("Mean confusion matrix:\n", mean_conf_mat)

c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:839: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_scorer.py", line 136, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Mirtha\AppData\Local\Programs\Python\

Cross-validation scores: [nan nan nan nan nan]
Mean Cross-validation score: nan


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [4]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf, X, y_encoded, cv=5)
conf_mat = confusion_matrix(y_encoded, y_pred)



ValueError: multilabel-indicator is not supported

In [32]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import make_scorer

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

# Define the Decision Tree classifier
clf = DecisionTreeClassifier(random_state=42)

# Define accuracy as the metric for scoring
scorer = make_scorer(accuracy_score)

# Perform K-fold cross validation
cv_scores = cross_val_score(clf, X, y_encoded, cv=5, scoring=scorer)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)

# Print the mean cross-validation score
print("Mean Cross-validation score:", np.mean(cv_scores))


Cross-validation scores: [1. 1. 1. 1. 1.]
Mean Cross-validation score: 1.0


c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [1]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import make_scorer

# Define the data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array(["low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium", "low", "medium", "high", "low", "medium"])

# One-hot encode the target variable
enc = OneHotEncoder(sparse=False)
y_encoded = enc.fit_transform(y.reshape(-1, 1))

# Define the Multinomial Naive Bayes classifier
clf = MultinomialNB()

# Define accuracy as the metric for scoring
scorer = make_scorer(accuracy_score)

# Perform K-fold cross validation
cv_scores = cross_val_score(clf, X, np.argmax(y_encoded, axis=1), cv=5, scoring=scorer)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)

# Print the mean cross-validation score
print("Mean Cross-validation score:", np.mean(cv_scores))


c:\Users\Mirtha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


NameError: name 'accuracy_score' is not defined

In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf, x, y, cv=10)
conf_mat = confusion_matrix(y, y_pred)